version: '3.8'

services:

  backend:
    build: ./services/backend_regimo
    ports:
      - "8000:8000"
    volumes:
      - ./services/backend_regimo:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"